# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go run filterInvalid.go -U

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: osmtogeojson
      run: npm install -g osmtogeojson

    - name: Convert to GeoJson
      run:  osmtogeojson missingRecycling.json > missingRecycling.geojson

    - name: Commit changes
      run: |
        git config --global user.email "pavel.beranek@gmx.com"
        git config --global user.name "BeranekP"
        git add missingRecycling.geojson
        git commit -m "Update data"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    

  
